"""update user authentication schema

Revision ID: dc0c538c2ff3
Revises: 4b4a656f0d6c
Create Date: 2026-08-31 16:06:35.412543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0c538c2ff3'
down_revision: Union[str, Sequence[str], None] = '4b4a656f0d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.Text(), server_default=sa.text("'email'"), nullable=False))
    op.alter_column('users', 'sub',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sub',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
