"""update user authentication schema (forget pass)

Revision ID: f161a6d2be2e
Revises: dc0c538c2ff3
Create Date: 2026-09-01 00:40:55.545199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f161a6d2be2e'
down_revision: Union[str, Sequence[str], None] = 'dc0c538c2ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
